base: 'https://api.pwa-demo.ddev.site'
frontendBase: 'https://pwa-demo.ddev.site'
frontendApiProxy: 'https://pwa-demo.ddev.site/headless'
frontendFileApi: 'https://pwa-demo.ddev.site/headless/fileadmin'
baseVariants:
  -
    base: 'https://api.t3pwa.com'
    condition: 'applicationContext == "Production/Production"'
    frontendBase: 'https://demo.t3pwa.com'
    frontendApiProxy: 'https://demo.t3pwa.com/headless'
    frontendFileApi: 'https://demo.t3pwa.com/headless/fileadmin'
headless: 1
languages:
  -
    languageId: 0
    title: English
    navigationTitle: English
    base: /
    locale: en_US.UTF8
    iso-639-1: en
    hreflang: en-US
    direction: ltr
    typo3Language: default
    flag: us
    enabled: true
  -
    languageId: 1
    title: Polish
    navigationTitle: Polish
    base: /pl/
    locale: pl_PL.UTF-8
    iso-639-1: pl
    hreflang: pl-PL
    direction: ltr
    typo3Language: default
    flag: pl
    fallbackType: fallback
    fallbacks: '0'
    enabled: true
  -
    languageId: 2
    title: German
    navigationTitle: Deutsch
    base: /de/
    locale: de_DE.UTF8
    iso-639-1: de
    hreflang: de-DE
    direction: ltr
    typo3Language: de
    flag: de
    fallbackType: fallback
    fallbacks: '0'
    enabled: true
rootPageId: 43
routeEnhancers:
  News:
    type: Extbase
    extension: News
    plugin: Pi1
    routes:
      - routePath: '/{news-title}'
        _controller: 'News::detail'
        _arguments:
          news-title: news
      - routePath: '/{page}'
        _controller: 'News::list'
        _arguments:
          page: 'currentPage'
    defaultController: 'News::list'
    defaults:
      page: '0'
    aspects:
      page:
        type: StaticRangeMapper
        start: '1'
        end: '100'
      news-title:
        type: PersistedAliasMapper
        tableName: tx_news_domain_model_news
        routeFieldName: path_segment
websiteTitle: 'TYPO3 Headless & PWA Demo'
